# this workflow will build CranSurvey for Deno Deploy, Cloudflare Workers, and Vercel.

name: Build

on:
    push:
      branches: [ "master" ]
    release:
      types: [ "published" ]

jobs:
    build:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install
              run: |
                yarn install
            - name: Build for Deno Deploy
              run: |
                NITRO_PRESET=deno yarn build
                mv .output deno
            - name: Build for Cloudflare Workers
                run: |
                    NITRO_PRESET=cloudflare yarn build
                    mv .output cloudflare
            - name: Build for Vercel
                run: |
                    NITRO_PRESET=vercel yarn build
                    mv .output vercel
            - name: Push
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.ACTION_GH_TOKEN }}
                    branch: dist
                    force: true
                    directory: .
                    commit_message: "Build Successfully"
                    committer: "CranSurvey Bot <cransurveybot@github.com>"
                